---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: 迁移存储数据时，使用 REST API 手动加入存储后端。迁移 VASA Provider 数据时，数据从现有的 Derby 数据库导出并导入 MongoDB 数据库。 
---
= 迁移 VASA 提供程序并更新 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照本节中的步骤，将 VASA 提供程序从ONTAP tools for VMware vSphere迁移到ONTAP tools for VMware vSphere，并更新 VMware Live Site Recovery 设备上的存储复制适配器 (SRA)。



== 迁移 VASA 提供程序的步骤

. 要在现有的适用ONTAP tools for VMware vSphere上启用 Derby PORT 1527，请启用 root 用户并通过 SSH 登录到 CLI。然后，运行以下命令：
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. ONTAP tools for VMware vSphere的 OVA。
. 添加要迁移到ONTAP tools for VMware vSphere的 vCenter Server 实例。请参阅link:../configure/add-vcenter.html["添加 vCenter Server 实例"]了解更多信息。
. 通过 vCenter Server API 将存储后端本地集成到ONTAP工具插件中。请参阅link:../configure/add-storage-backend.html["使用 vSphere 客户端界面添加存储后端"]了解更多信息。
. 获取访问令牌以验证 REST API 请求。请使用以下示例，并将变量替换为特定于您环境的值。
+
+



[listing]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
复制并保存响应中返回的访问令牌。。从 Swagger 或 Postman 发出以下 API 进行迁移。

+

[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
您可以通过以下网址访问 Swagger： `\https://$FQDN_IP_PORT/` ， 例如： `\https://10.67.25.33:8443/` 。

+

[]
====
HTTP 方法和端点

此 REST API 调用使用以下方法和端点。

|===


| HTTP 方法 | *小路* 


| POST | /api/v1 
|===
*加工类型*

异步

*Curl 示例*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
--header 'x-auth: <auth_token>' \
--header 'Content-Type: application/json' \
--data '{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "******"
  },
  "database_password": "******"
}'
----
其他版本迁移的请求主体：

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
JSON 输出示例

系统返回一个作业对象。保存作业标识符以便在下一步中使用。

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. 在 Swagger 中使用以下 URI 检查状态：
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<migration_id>?includeSubJobsAndTasks=true`
----
+
作业完成后，请查看作业响应中的迁移报告。

. 将ONTAP tools for VMware vSphere添加到 vCenter Server。
. 使用ONTAP tools for VMware vSphere 的VASA 提供程序。有关说明，请参阅link:../configure/registration-process.html["注册 VASA 提供程序"]。
. 注册后，请在 vSphere Client 的“存储提供程序”下验证 VASA 提供程序的名称及其状态。VASA 提供商应在线显示，确认注册成功。
. link:../manage/enable-services.html["启用 VASA Provider"]ONTAP tools for VMware vSphere上的服务。
. 请按照以下步骤停止ONTAP tools for VMware vSphere：
+
.. 在ONTAP工具 9.x 中，打开 Web 控制台。
.. 访问维护控制台。
.. 进入 `1`选择“应用程序配置”菜单。
.. 进入 `5`停止 VASA Provider 和 SRA 服务。
.. 在 vSphere Client 中，导航至“清单”>“存储提供程序”。
.. 从存储后端选择ONTAP工具 9.x VASA 提供程序，然后单击“删除”。
+
旧 VASA 提供程序停止后，vCenter Server 将故障转移到ONTAP tools for VMware vSphere。所有数据存储库和虚拟机均可访问，并由适用于ONTAP tools for VMware vSphere提供服务。



. 迁移后的 NFS 和 VMFS 数据存储会在数据存储发现作业完成后出现在ONTAP tools for VMware vSphere中，该作业可能需要长达 30 分钟。在概览页面上检查它们的可见性。
. 使用 Swagger 或 Postman 中的以下 API 执行补丁迁移：
+
[]
====
HTTP 方法和端点

此 REST API 调用使用以下方法和端点。

|===


| HTTP 方法 | *小路* 


| 修补 | /api/v1 
|===
*加工类型*

异步

请在 Swagger 中使用以下 URI：

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Curl 示例*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
JSON 输出示例

返回一个作业对象。您应该保存作业标识符以便在下一步中使用它。

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+
修补操作请求体为空。




NOTE: UUID 是响应迁移后 API 返回的迁移 UUID。

运行补丁迁移API后，所有虚拟机都符合存储策略。

.下一步
完成迁移并将ONTAP Tools 10.4 注册到 vCenter Server 后，请按照以下步骤操作：

* 等待*发现*完成，系统会自动在所有主机上刷新证书。
* 等待数据存储区和虚拟机操作开始。等待时间取决于主机、数据存储和虚拟机的数量。如果您不等待，您可能会偶尔看到失败。


升级后，如果虚拟机的合规性状态已过时，请使用以下步骤重新应用存储策略：

. 转到数据存储并选择*摘要*>*虚拟机存储策略*。
+
系统显示*虚拟机存储策略合规性*下的合规性状态为*过时*。

. 选择存储虚拟机策略和相应的虚拟机。
. 选择*应用*。
+
*虚拟机存储策略合规性*下的合规性状态显示为合规。相关信息

+
** link:../concepts/rbac-learn-about.html["了解适用于ONTAP tools for VMware vSphere"]
** link:../upgrade/upgrade-ontap-tools.html["将适用于ONTAP tools for VMware vSphere升级到 10.4"]






== 更新存储复制适配器（SRA）的步骤

.开始之前
在恢复计划中，受保护站点是指虚拟机当前运行的位置，而恢复站点是指虚拟机将被恢复到的位置。SRM界面显示恢复计划的状态，其中包含有关受保护站点和恢复站点的详细信息。在恢复计划中，“*CleanupP*”和“*Reprotect*”按钮处于禁用状态，而“TEST”和“RUN”按钮保持启用状态。这表示该站点已准备好进行数据恢复。在迁移 SRA 之前，请验证一个站点处于受保护状态，另一个站点处于恢复状态。


NOTE: 如果故障转移已完成但重新保护仍处于待定状态，请勿开始迁移。确保在继续迁移之前重新保护过程已完成。如果正在进行测试故障转移，请清理测试故障转移并开始迁移。

. 按照以下步骤删除 VMware Site Recovery 中适用于 VMware vSphere 9.xx 的ONTAP工具 SRA 适配器：
+
.. 转到 VMware Live Site Recovery 配置管理页面
.. 转到*存储复制适配器*部分。
.. 从省略号菜单中选择*重置配置*。
.. 从省略号菜单中选择*删除*。


. 在保护站点和恢复站点上执行这些步骤。
+
.. link:../manage/enable-services.html["ONTAP tools for VMware vSphere"]
.. 使用以下步骤ONTAP tools for VMware vSpherelink:../protect/configure-on-srm-appliance.html["在 VMware Live Site Recovery 设备上配置 SRA"]。
.. 在 VMware Live Site Recovery 用户界面页面，执行 *发现阵列* 和 *发现设备* 操作，确认设备显示与迁移前一致。



