---
permalink: protect/configure-array-manager.html 
sidebar: sidebar 
keywords:  
summary: '您可以使用 VMware Live Site Recovery 的阵列管理器向导配置存储复制适配器 (SRA)，以实现 VMware Live Site Recovery 与存储虚拟机 (SVM) 之间的交互。' 
---
= 使用阵列管理器配置 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 VMware Live Site Recovery 的阵列管理器向导配置存储复制适配器 (SRA)，以实现 VMware Live Site Recovery 与存储虚拟机 (SVM) 之间的交互。

.开始之前
* 您应该已经在 VMware Live Site Recovery 中将受保护的站点和恢复站点配对。
* 在配置阵列管理器之前，您应该已经配置了板载存储。
* 您应该已经配置并复制了受保护站点和恢复站点之间的SnapMirror关系。
* 您应该已启用 SVM 管理 LIF 以启用多租户。


SRA支持集群级别管理和SVM级别管理。如果在集群级别添加存储，则可以发现集群中的所有 SVM 并对其执行操作。如果在 SVM 级别添加存储，则您只能管理该特定的 SVM。

.步骤
. 在 VMware Live Site Recovery 中，选择 *阵列管理器* > *添加阵列管理器*。
. 输入以下信息来描述 VMware Live Site Recovery 中的阵列：
+
.. 在“显示名称”字段中输入一个名称来标识阵列管理器。
.. 在 *SRA 类型* 字段中，选择 * NetApp Storage Replication Adapter for ONTAP*。
.. 输入连接到集群或 SVM 的信息：
+
*** 如果您要连接到集群，则应输入集群管理 LIF。
*** 如果您直接连接到 SVM，则应输入 SVM 管理 LIF 的 IP 地址。
+

NOTE: 配置阵列管理器时，您应该对存储系统使用与在适用ONTAP tools for VMware vSphere中安装存储系统时相同的连接（IP 地址）。例如，如果阵列管理器配置是 SVM 范围的，则应在 SVM 级别添加适用于ONTAP tools for VMware vSphere下的存储。



.. 如果连接到集群，请在 *SVM 名称* 字段中指定 SVM 名称，或者将其留空以管理集群中的所有 SVM。
.. 在“卷包含列表”字段中输入要发现的卷。
+
您可以在受保护站点输入源卷，在恢复站点输入复制的目标卷。

+
例如，如果您想要发现与卷 dst_vol1 具有SnapMirror关系的卷 src_vol1，则应在受保护站点字段中指定 src_vol1，并在恢复站点字段中指定 dst_vol1。

.. *（可选）*在“卷排除列表”字段中输入要从发现中排除的卷。
+
您可以在受保护站点输入源卷，在恢复站点输入复制的目标卷。

+
例如，如果要排除与卷 _dst_vol1_ 具有SnapMirror关系的卷 _src_vol1_，则应在受保护站点字段中指定 _src_vol1_，并在恢复站点字段中指定 _dst_vol1_。



. 选择“下一步”。
. 验证阵列是否被发现并显示在“添加阵列管理器”窗口的底部，然后选择“*完成*”。


您可以使用适当的 SVM 管理 IP 地址和凭据对恢复站点执行相同的步骤。在添加阵列管理器向导的启用阵列对屏幕上，您应该验证是否选择了正确的阵列对，以及它是否显示为已准备好启用。
