---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: '在为 VMware Live Site Recovery 运行存储复制适配器 (SRA) 之前，您应该设置存储系统。' 
---
= 为 SAN 和 NAS 环境配置 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在运行 VMware Live Site Recovery 的存储复制适配器 (SRA) 之前，您应该设置存储系统。



== 为 SAN 环境配置 SRA

.开始之前
您应该在受保护站点和恢复站点上安装以下程序：

* VMware Live Site Recovery
+
有关安装 VMware Live Site Recovery 的文档位于 VMware 网站上。

+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["关于 VMware Live Site Recovery"]

* SRA
+
该适配器安装在 VMware Live Site Recovery 上。



.步骤
. 验证主 ESXi 主机是否连接到受保护站点上主存储系统中的 LUN。
. 验证 LUN 是否位于具有 `ostype`在主存储系统上将选项设置为_VMware_。
. 验证恢复站点上的 ESXi 主机是否与存储虚拟机 (SVM) 具有适当的 iSCSI 连接。辅助站点 ESXi 主机应该能够访问辅助站点存储，主站点 ESXi 主机应该能够访问主站点存储。
+
您可以通过验证 ESXi 主机是否在 SVM 上连接了本地 LUN 或 `iscsi show initiators`在 SVM 上执行命令。检查 ESXi 主机中映射 LUN 的 LUN 访问以验证 iSCSI 连接。





== 为 NAS 环境配置 SRA

.开始之前
您应该在受保护站点和恢复站点上安装以下程序：

* VMware Live Site Recovery
+
有关安装 VMware Live Site Recovery 的文档可在 VMware 网站上找到。

+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["关于 VMware Live Site Recovery"]

* SRA
+
该适配器安装在 VMware Live Site Recovery 和 SRA 服务器上。



.步骤
. 验证受保护站点上的数据存储区是否包含在 vCenter Server 中注册的虚拟机。
. 验证受保护站点上的 ESXi 主机是否已从存储虚拟机 (SVM) 挂载 NFS 导出卷。
. 使用阵列管理器向导将阵列添加到 VMware Live Site Recovery 时，请验证“*NFS 地址*”字段中指定的有效地址（例如，存在 NFS 导出的 IP 地址或 FQDN）。请勿在“*NFS 地址*”字段中使用 NFS 主机名。
. 使用 `ping`命令，以验证主机是否具有可访问用于从 SVM 提供 NFS 导出服务的 IP 地址的 VMkernel 端口。

