---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 您应该创建保护组来保护受保护站点上的一组虚拟机。 
---
= 配置受保护站点和恢复站点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应该创建保护组来保护受保护站点上的一组虚拟机。

添加新的数据存储区时，您可以将其添加到现有的数据存储区组中，也可以添加新的数据存储区并创建新的卷或一致性组以进行保护。将新的数据存储区添加到受保护的一致性组或卷后，更新SnapMirror并在受保护站点和恢复站点上执行存储发现。您可以手动或按计划运行发现，以确保检测到并保护新的数据存储区。



== 将受保护站点和恢复站点配对

您应该将使用 vSphere Client 创建的受保护站点和恢复站点配对，以启用存储复制适配器 (SRA) 来发现存储系统。


NOTE: 存储复制适配器 (SRA) 支持具有自动故障转移双工类型的一个同步关系的扇出以及一致性组上的异步关系SnapMirror 。但是，不支持在一致性组上使用两个异步SnapMirror进行扇出或在卷上使用扇出 SnapMirror 进行扇出。

.开始之前
* 您应该在受保护站点和恢复站点上安装 VMware Live Site Recovery。
* 您应该在受保护站点和恢复站点上安装 SRA。


.步骤
. 在 vSphere Client 主页上双击 *Site Recovery*，然后选择 *Sites*。
. 选择*对象* > *操作* > *配对站点*。
. 在*配对站点恢复管理器服务器*对话框中，输入受保护站点的 Platform Services Controller 的地址，然后选择*下一步*。
. 在“选择 vCenter Server”部分中，执行以下操作：
+
.. 验证受保护站点的 vCenter Server 是否显示为匹配的候选配对。
.. 输入 SSO 管理凭据，然后选择 *完成*。


. 如果出现提示，请选择“是”接受安全证书。


.结果
受保护站点和恢复站点都将出现在“对象”对话框中。



== 配置保护组

.开始之前
您应确保源站点和目标站点均已配置以下内容：

* 安装了相同版本的 VMware Live Site Recovery
* 虚拟机
* 配对的受保护站点和恢复站点
* 源数据存储区和目标数据存储区应安装在各自的站点上


.步骤
. 登录到 vCenter Server 并选择“Site Recovery”>“Protection Groups”。
. 在“保护组”窗格中，选择“新建”。
. 指定保护组的名称和描述、方向，然后选择*下一步*。
. 在“类型”字段中，选择“数据存储组（基于阵列的复制）”作为 NFS 和 VMFS 数据存储区的“类型”字段选项...*。故障域仅包含已启用复制的 SVM。系统会显示仅实施了对等连接且没有问题的 SVM。
. 在“复制组”选项卡中，选择已启用的阵列对或具有您配置的虚拟机的复制组，然后选择“*下一步*”。
+
复制组上的所有虚拟机均添加到保护组。

. 您可以选择现有的恢复计划，也可以通过选择“添加到新恢复计划”来创建新的恢复计划。
. 在“即将完成”选项卡中，查看您创建的保护组的详细信息，然后选择“完成”。

