---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 存储后端是 ESXi 主机用于数据存储的系统。 
---
= 添加存储后端
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
添加存储后端使您能够加入ONTAP集群。

*关于此任务*

如果在多租户设置中，vCenter 充当具有关联 SVM 的租户，则使用ONTAP工具管理器添加集群。将存储后端与 vCenter Server 关联，以将其全局映射到已加入的 vCenter Server 实例。 vCenter 租户必须加入所需的存储虚拟机 (SVM)。这使得 SVM 用户能够配置vVols数据存储。您可以使用 SVM 在 vCenter 中添加存储。

使用ONTAP工具用户界面添加具有集群或 SVM 凭据的本地存储后端。这些存储后端仅限于单个 vCenter。在本地使用集群凭据时，关联的 SVM 会自动映射到 vCenter 来管理vVols或 VMFS。对于 VMFS 管理（包括 SRA）， ONTAP工具支持 SVM 凭据，而无需全局集群。

[role="tabbed-block"]
====
.使用ONTAP工具管理器
--

NOTE: 在多租户设置中，您可以全局添加存储后端集群，并在本地添加 SVM 以使用 SVM 用户凭据。

.步骤
. 从 Web 浏览器启动ONTAP工具管理器： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于ONTAP tools for VMware vSphere管理员凭据登录。
. 从侧边栏中选择*存储后端*。
. 添加存储后端并提供服务器 IP 地址或 FQDN、用户名和密码详细信息。
+

NOTE: 支持 IPv4 和 IPv6 地址管理 LIF。



--
.使用 vSphere 客户端用户界面
--

NOTE: 通过 vSphere 客户端用户界面配置存储后端时，需要注意的是， vVols数据存储不支持直接添加 SVM 用户。

. 登录到 vSphere 客户端。
. 在快捷方式页面中，选择插件部分下的* NetApp ONTAP工具*。
. 从侧边栏中选择*存储后端*。
. 添加存储后端并提供服务器 IP 地址、用户名、密码和端口详细信息。
+

NOTE: 要直接添加 SVM 用户，您可以添加基于集群的凭据以及 IPv4 和 IPv6 地址管理 LIF，或者使用 SVM 管理 LIF 提供基于 SVM 的凭据。



.下一步是什么？
列表刷新，您可以在列表中看到新添加的存储后端。

--
====