---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: '您可以使用适用ONTAP tools for VMware vSphere安装适用于 VMware vStorage APIs for Array Integration (VAAI) 的NetApp NFS 插件。' 
---
= 安装 NFS VAAI 插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS vStorage API for Array Integration (NFS VAAI) 插件是集成 VMware vSphere 和 NFS 存储阵列的软件组件。使用适用ONTAP tools for VMware vSphere安装 NFS VAAI 插件，以利用 NFS 存储阵列的高级功能将某些与存储相关的操作从 ESXi 主机卸载到存储阵列本身。

.开始之前
* 下载 https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["适用于 VMware VAAI 的 NetApp NFS 插件"]安装包。
* 确保您拥有 ESXi 主机和 vSphere 7.0U3 最新补丁或更高版本以及ONTAP 9.14.1 或更高版本。
* 挂载 NFS 数据存储。


.步骤
. 登录到 vSphere 客户端。
. 在插件部分下选择 *快捷方式* > * NetApp ONTAP工具*。
. 选择“*设置*”>“*NFS VAAI 工具*”。
. 当 VAAI 插件上传到 vCenter Server 时，在 *现有版本* 部分中选择 *更改*。如果 VAAI 插件未上传到 vCenter Server，请选择*上传*按钮。
. 浏览并选择 `.vib`文件并选择*上传*将文件上传到ONTAP工具。
. 选择*在 ESXI 主机上安装*，选择要安装 NFS VAAI 插件的 ESXi 主机，然后选择*安装*。
+
仅显示符合插件安装条件的 ESXi 主机。您可以在 vSphere Web Client 的最近任务部分监控安装进度。

. 安装后手动重新启动 ESXi 主机。
+
当 VMware 管理员重新启动 ESXi 主机时，ONTAP tools for VMware vSphere会自动检测并启用 NFS VAAI 插件。



.下一步是什么？
安装 NFS VAAI 插件并重新启动 ESXi 主机后，您需要为 VAAI 副本卸载配置正确的 NFS 导出策略。在 NFS 环境中配置 VAAI 时，请根据以下要求配置导出策略规则：

* 相关的ONTAP卷需要允许 NFSv4 调用。
* 根用户应保持为根用户，并且所有连接父卷中都应允许使用 NFSv4。
* 需要在相关的 NFS 服务器上设置 VAAI 支持选项。


有关该过程的更多信息，请参阅 https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["为 VAAI 副本卸载配置正确的 NFS 导出策略"]知识库文章。

.相关信息
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["支持 VMware vStorage over NFS"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["启用或禁用 NFSv4.0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["ONTAP对 NFSv4.2 的支持"]
