---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 您可以编辑受保护主机集群的SnapMirror关系。您可以添加、修改和删除关系。但是，您不能编辑一致性组名称。 
---
= 修改受保护的主机集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以执行以下任务作为修改保护的一部分。您可以在同一工作流程中执行所有更改。

* 向受保护的集群添加新的数据存储或主机。
* 将新的SnapMirror关系添加到保护设置中。
* 从保护设置中删除现有的SnapMirror关系。
* 修改现有的SnapMirror关系。




== 监控主机集群保护

使用此过程来监控主机群集保护的状态。您可以监控每个受保护的主机集群及其保护状态、 SnapMirror关系、数据存储和相应的SnapMirror状态。

.步骤
. 登录到 vSphere 客户端。
. 导航到 * NetApp ONTAP工具* > *保护* > *主机集群关系*。
+
保护栏下方的图标显示保护状态

. 将鼠标悬停在图标上可以查看更多详细信息。




== 添加新的数据存储或主机

使用此过程来保护新添加的数据存储区或主机。您可以使用 vCenter 本机用户界面将新主机添加到受保护的群集或在主机群集上创建新的数据存储区。

.步骤
. 登录到 vSphere 客户端。
. 要编辑受保护集群的属性，您可以
+
.. 导航到 * NetApp ONTAP工具 * > * 保护 * > * 主机集群关系 *，选择集群对应的省略号菜单，然后选择 * 编辑 * 或
.. 右键单击主机集群并选择 * NetApp ONTAP工具* > *保护集群*。


. 如果您已在 vCenter 本机用户界面中创建了数据存储区，则该数据存储区将显示为不受保护。用户界面在对话框中显示集群中的所有数据存储及其保护状态。选择*保护*按钮以启用完全保护。
. 如果您添加了新的 ESXi 主机，则保护状态显示为部分受保护。选择SnapMirror设置下的省略号菜单，然后选择 *编辑* 来设置新添加的 ESXi 主机的接近度。
+

NOTE: 对于异步类型关系，由于您无法将第三级站点的目标 SVM 添加到同一个ONTAP工具实例，因此不支持编辑操作。但是，您可以使用目标 SVM 的系统管理器或 CLI 来更改关系配置。

. 进行必要的更改后，选择“*保存*”。
. 您可以在“保护集群”窗口中看到更改。


vCenter 任务已创建，您可以在“最近任务”面板中跟踪进度。



== 添加新的SnapMirror关系

.步骤
. 登录到 vSphere 客户端。
. 要编辑受保护集群的属性，您可以
+
.. 导航到 * NetApp ONTAP工具 * > * 保护 * > * 主机集群关系 *，选择集群对应的省略号菜单，然后选择 * 编辑 * 或
.. 右键单击主机集群并选择 * NetApp ONTAP工具* > *保护集群*。


. 选择*添加关系*。
. 添加新的关系作为*异步*或*AutomatedFailOverDuplex*策略类型。
. 选择*保护*。
+
您可以在“保护集群”窗口中看到更改。



vCenter 任务已创建，您可以在“最近任务”面板中跟踪进度。



== 删除现有的SnapMirror关系

要删除异步SnapMirror关系，应将辅助站点 SVM 或集群添加为ONTAP tools for VMware vSphere上的存储后端。您无法删除所有SnapMirror关系。当您删除关系时， ONTAP集群上的相应关系也会被删除。删除 AutomatedFailOverDuplex SnapMirror关系时，目标上的数据存储库将取消映射，并且一致性组、LUN、卷和 igroup 将从目标ONTAP集群中删除。

删除关系会触发辅助站点上的重新扫描，以从主机中删除未映射的 LUN 作为活动路径。

.步骤
. 登录到 vSphere 客户端。
. 要编辑受保护集群的属性，您可以
+
.. 导航到 * NetApp ONTAP工具 * > * 保护 * > * 主机集群关系 *，选择集群对应的省略号菜单，然后选择 * 编辑 * 或
.. 右键单击主机集群并选择 * NetApp ONTAP工具* > *保护集群*。


. 选择SnapMirror设置下的省略号菜单，然后选择*删除*。


vCenter 任务已创建，您可以在“最近任务”面板中跟踪进度。



== 修改现有的SnapMirror关系

要修改异步SnapMirror关系，应将辅助站点 SVM 或集群添加为ONTAP tools for VMware vSphere上的存储后端。如果是 AutomatedFailOverDuplex SnapMirror关系，则可以在统一配置的情况下修改主机接近度，在非统一配置的情况下修改主机访问。您不能互换异步和 AutomatedFailOverDuplex 策略类型。您可以设置集群上新发现的主机的接近度或访问权限。


NOTE: 您无法编辑现有的异步SnapMirror关系。

.步骤
. 登录到 vSphere 客户端。
. 要编辑受保护集群的属性，您可以
+
.. 导航到 * NetApp ONTAP工具 * > * 保护 * > * 主机集群关系 *，选择集群对应的省略号菜单，然后选择 * 编辑 * 或
.. 右键单击主机集群并选择 * NetApp ONTAP工具* > *保护集群*。


. 如果选择了 AutomatedFailOverDuplex 策略类型，请添加主机邻近度或主机访问详细信息。
. 选择*保护*按钮。


vCenter 任务已创建，您可以在“最近任务”面板中跟踪进度。
